"""add expense management module

Revision ID: 059e3681d27f
Revises: 5be032f02da0
Create Date: 2026-03-27 06:11:18.949139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059e3681d27f'
down_revision = '5be032f02da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.Enum('OPERATIONS', 'TRANSPORT', 'MEETING', 'COMMUNICATION', 'BANK_CHARGES', 'WELFARE', 'LOAN_PROCESSING', 'INVESTMENT', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('status', sa.Enum('RECORDED', 'APPROVED', 'CANCELLED', name='expensestatus'), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expense_chama_category', ['chama_id', 'category'], unique=False)
        batch_op.create_index('ix_expense_chama_date', ['chama_id', 'expense_date'], unique=False)
        batch_op.create_index('ix_expense_chama_status', ['chama_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_reference_code'))
        batch_op.drop_index(batch_op.f('ix_expenses_chama_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_index('ix_expense_chama_status')
        batch_op.drop_index('ix_expense_chama_date')
        batch_op.drop_index('ix_expense_chama_category')

    op.drop_table('expenses')
    # ### end Alembic commands ###
