"""Initial migration for SQLite

Revision ID: 28b2045534ad
Revises: 
Create Date: 2025-10-26 18:58:04.628264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b2045534ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.Column('loan_interest_rate', sa.Float(), nullable=True),
    sa.Column('max_loan_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chamas')),
    sa.UniqueConstraint('name', name=op.f('uq_chamas_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_audit_logs_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('contribution_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank', 'cash', 'mobile_money', name='payment_methods'), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'cancelled', name='contribution_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_contributions_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contributions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_contributions_transaction_id'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'complaint', 'suggestion', 'appreciation', name='feedback_categories'), nullable=True),
    sa.Column('status', sa.Enum('new', 'read', 'addressed', 'closed', name='feedback_status'), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_feedback_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'disbursed', 'active', 'completed', 'defaulted', name='loan_status'), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('disbursed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_repayment', sa.Float(), nullable=True),
    sa.Column('monthly_repayment', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_loans_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('chairperson', 'treasurer', 'secretary', 'member', name='member_role'), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', 'suspended', name='member_status'), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.Column('last_contribution_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_memberships_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'chama_id', name='unique_membership')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('info', 'warning', 'success', 'error', 'reminder', name='notification_types'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_notifications_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_password_reset_tokens_token'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_types'), nullable=True),
    sa.Column('id_number', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('id_number', name=op.f('uq_profiles_id_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('contributions', 'loans', 'members', 'financial', 'voting', name='report_types'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_end', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_reports_chama_id_chamas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vote_type', sa.Enum('yes_no', 'multiple_choice', 'election', name='vote_types'), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='vote_status'), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], name=op.f('fk_votes_chama_id_chamas')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_votes_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes'))
    )
    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank', 'cash', 'mobile_money', name='payment_methods'), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'cancelled', name='repayment_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_repayments_loan_id_loans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_repayments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repayments')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_repayments_transaction_id'))
    )
    op.create_table('vote_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], name=op.f('fk_vote_options_vote_id_votes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_options'))
    )
    op.create_table('vote_casts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['vote_options.id'], name=op.f('fk_vote_casts_option_id_vote_options')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vote_casts_user_id_users')),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], name=op.f('fk_vote_casts_vote_id_votes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_casts')),
    sa.UniqueConstraint('vote_id', 'user_id', name='unique_vote_cast')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_casts')
    op.drop_table('vote_options')
    op.drop_table('repayments')
    op.drop_table('votes')
    op.drop_table('reports')
    op.drop_table('profiles')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_table('memberships')
    op.drop_table('loans')
    op.drop_table('feedback')
    op.drop_table('contributions')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('chamas')
    # ### end Alembic commands ###
