"""initial smart chama schema

Revision ID: 45deb7652be9
Revises: 
Create Date: 2026-03-12 14:59:23.989837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45deb7652be9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('loan_interest_rate >= 0', name='check_chama_loan_interest_rate_non_negative'),
    sa.CheckConstraint('max_loan_amount >= 0', name='check_chama_max_loan_amount_non_negative'),
    sa.CheckConstraint('monthly_contribution >= 0', name='check_chama_monthly_contribution_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamas_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'chairperson', 'treasurer', 'secretary', 'member', name='user_roles'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_type', sa.Enum('regular', 'penalty', 'registration', 'special', name='contribution_types'), nullable=False),
    sa.Column('contribution_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank', 'cash', 'mobile_money', name='contribution_payment_methods'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'cancelled', name='contribution_statuses'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_contribution_amount_positive'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_user_id'), ['user_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('operations', 'meeting', 'transport', 'communication', 'bank_charges', 'investment', 'legal', 'other', name='expense_categories'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank', 'cash', 'mobile_money', name='expense_payment_methods'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_expense_amount_positive'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_recorded_by_id'), ['recorded_by_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'complaint', 'suggestion', 'appreciation', name='feedback_categories'), nullable=False),
    sa.Column('status', sa.Enum('new', 'read', 'addressed', 'closed', name='feedback_statuses'), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment_type', sa.Enum('business', 'real_estate', 'sacco', 'shares', 'bonds', 'money_market', 'other', name='investment_types'), nullable=False),
    sa.Column('amount_invested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_return_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('realized_profit_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'matured', 'closed', 'loss', name='investment_statuses'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_invested >= 0', name='check_investment_amount_invested_non_negative'),
    sa.CheckConstraint('current_value >= 0', name='check_investment_current_value_non_negative'),
    sa.CheckConstraint('expected_return_rate >= 0', name='check_investment_expected_return_rate_non_negative'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_created_by'), ['created_by'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'disbursed', 'active', 'completed', 'defaulted', name='loan_statuses'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_repayment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_repayment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_loan_amount_positive'),
    sa.CheckConstraint('interest_rate >= 0', name='check_loan_interest_rate_non_negative'),
    sa.CheckConstraint('term_months > 0', name='check_loan_term_months_positive'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    op.create_table('member_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('total_contributed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_loans_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_repaid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_dividends_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalties', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding_loan_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_position', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chama_id', name='uq_member_balances_user_id_chama_id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('chairperson', 'treasurer', 'secretary', 'member', name='membership_roles'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', 'suspended', name='membership_statuses'), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_contribution_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('monthly_contribution >= 0', name='check_membership_monthly_contribution_non_negative'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chama_id', name='uq_memberships_user_id_chama_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('info', 'warning', 'success', 'error', 'reminder', name='notification_types'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_types'), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('contributions', 'loans', 'members', 'financial', 'voting', 'investments', 'expenses', 'dividends', name='report_types'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vote_type', sa.Enum('yes_no', 'multiple_choice', 'election', name='vote_types'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='vote_statuses'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_created_by'), ['created_by'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('declared_by', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('investment_profit', 'surplus', 'interest_income', 'other', name='dividend_source_types'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'cancelled', name='dividend_statuses'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('declared_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_dividend_amount_non_negative'),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['declared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividends_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_declared_by'), ['declared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_investment_id'), ['investment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_user_id'), ['user_id'], unique=False)

    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'bank', 'cash', 'mobile_money', name='repayment_payment_methods'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'cancelled', name='repayment_statuses'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_paid > 0', name='check_repayment_amount_paid_positive'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repayments_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repayments_user_id'), ['user_id'], unique=False)

    op.create_table('vote_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'option_text', name='uq_vote_options_vote_id_option_text')
    )
    with op.batch_alter_table('vote_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_options_vote_id'), ['vote_id'], unique=False)

    op.create_table('vote_casts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['vote_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'user_id', name='uq_vote_casts_vote_id_user_id')
    )
    with op.batch_alter_table('vote_casts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_casts_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_casts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_casts_vote_id'), ['vote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_casts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_casts_vote_id'))
        batch_op.drop_index(batch_op.f('ix_vote_casts_user_id'))
        batch_op.drop_index(batch_op.f('ix_vote_casts_option_id'))

    op.drop_table('vote_casts')
    with op.batch_alter_table('vote_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_options_vote_id'))

    op.drop_table('vote_options')
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repayments_user_id'))
        batch_op.drop_index(batch_op.f('ix_repayments_loan_id'))

    op.drop_table('repayments')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividends_user_id'))
        batch_op.drop_index(batch_op.f('ix_dividends_investment_id'))
        batch_op.drop_index(batch_op.f('ix_dividends_declared_by'))
        batch_op.drop_index(batch_op.f('ix_dividends_chama_id'))

    op.drop_table('dividends')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_created_by'))
        batch_op.drop_index(batch_op.f('ix_votes_chama_id'))

    op.drop_table('votes')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_chama_id'))

    op.drop_table('reports')
    op.drop_table('profiles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_chama_id'))

    op.drop_table('notifications')
    op.drop_table('memberships')
    op.drop_table('member_balances')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))
        batch_op.drop_index(batch_op.f('ix_loans_chama_id'))

    op.drop_table('loans')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_created_by'))
        batch_op.drop_index(batch_op.f('ix_investments_chama_id'))

    op.drop_table('investments')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_chama_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_chama_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_chama_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_chama_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamas_name'))

    op.drop_table('chamas')
    # ### end Alembic commands ###
