"""add dividend distribution module

Revision ID: 5be032f02da0
Revises: f76fcd74fa43
Create Date: 2026-03-27 04:53:37.446664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be032f02da0'
down_revision = 'f76fcd74fa43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DISTRIBUTED', 'CANCELLED', name='dividendstatus'), nullable=False),
    sa.Column('distribution_method', sa.Enum('EQUAL', 'PROPORTIONAL_CONTRIBUTION', name='dividenddistributionmethod'), nullable=False),
    sa.Column('distribution_date', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index('ix_dividend_chama_date', ['chama_id', 'distribution_date'], unique=False)
        batch_op.create_index('ix_dividend_chama_status', ['chama_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_distribution_method'), ['distribution_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_status'), ['status'], unique=False)

    op.create_table('dividend_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dividend_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='dividendallocationstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dividend_id'], ['dividends.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dividend_id', 'user_id', name='uq_dividend_allocation_user')
    )
    with op.batch_alter_table('dividend_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_dividend_allocation_dividend_status', ['dividend_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_allocations_dividend_id'), ['dividend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_allocations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_allocations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividend_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_dividend_allocations_status'))
        batch_op.drop_index(batch_op.f('ix_dividend_allocations_dividend_id'))
        batch_op.drop_index('ix_dividend_allocation_dividend_status')

    op.drop_table('dividend_allocations')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividends_status'))
        batch_op.drop_index(batch_op.f('ix_dividends_distribution_method'))
        batch_op.drop_index(batch_op.f('ix_dividends_chama_id'))
        batch_op.drop_index('ix_dividend_chama_status')
        batch_op.drop_index('ix_dividend_chama_date')

    op.drop_table('dividends')
    # ### end Alembic commands ###
