"""initial migrations

Revision ID: f76fcd74fa43
Revises: 
Create Date: 2026-03-26 17:38:36.228378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76fcd74fa43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'DEACTIVATED', name='useraccountstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deactivated', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'SUSPENDED', name='chamastatus'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('contribution_frequency', sa.String(length=50), nullable=True),
    sa.Column('base_contribution_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamas_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamas_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_chamas_status'), ['status'], unique=False)

    op.create_table('chama_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('role_to_assign', sa.Enum('ADMIN', 'TREASURER', 'SECRETARY', 'CHAIRPERSON', 'MEMBER', name='membershiprole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitestatus'), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chama_id', 'email', 'status', name='uq_pending_invite_per_email_chama')
    )
    with op.batch_alter_table('chama_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chama_invites_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chama_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_chama_invites_invited_user_id'), ['invited_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chama_invites_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chama_invites_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chama_invites_token'), ['token'], unique=True)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contribution_date', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index('ix_contribution_chama_user_date', ['chama_id', 'user_id', 'contribution_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_user_id'), ['user_id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment_type', sa.Enum('STOCKS', 'BONDS', 'MONEY_MARKET', 'SACCO', 'REAL_ESTATE', 'BUSINESS', 'FIXED_DEPOSIT', 'OTHER', name='investmenttype'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACTIVE', 'CLOSED', 'CANCELLED', name='investmentstatus'), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_return_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('invested_at', sa.DateTime(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index('ix_investment_chama_status', ['chama_id', 'status'], unique=False)
        batch_op.create_index('ix_investment_chama_type', ['chama_id', 'investment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_investment_type'), ['investment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_status'), ['status'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('borrower_user_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DISBURSED', 'PARTIALLY_REPAID', 'REPAID', 'DEFAULTED', 'CANCELLED', name='loanstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['borrower_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('ix_loan_chama_borrower_status', ['chama_id', 'borrower_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_borrower_user_id'), ['borrower_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TREASURER', 'SECRETARY', 'CHAIRPERSON', 'MEMBER', name='membershiprole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'PENDING', 'SUSPENDED', 'LEFT', 'REMOVED', name='membershipstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chama_id', name='uq_membership_user_chama')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_membership_user_chama_status', ['user_id', 'chama_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED', name='pollstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_chama_id'), ['chama_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_polls_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('USER_CREATED', 'USER_UPDATED', 'USER_SOFT_DELETED', 'USER_RESTORED', 'USER_DEACTIVATED', 'CHAMA_CREATED', 'CHAMA_UPDATED', 'MEMBERSHIP_CREATED', 'MEMBERSHIP_UPDATED', 'MEMBERSHIP_SUSPENDED', 'MEMBERSHIP_REMOVED', 'MEMBERSHIP_RESTORED', 'INVITE_CREATED', 'INVITE_ACCEPTED', 'INVITE_REVOKED', 'CONTRIBUTION_RECORDED', 'CONTRIBUTION_UPDATED', 'CONTRIBUTION_DELETED', 'LOAN_APPLIED', 'LOAN_APPROVED', 'LOAN_REJECTED', 'LOAN_DISBURSED', 'LOAN_UPDATED', 'LOAN_DELETED', 'LOAN_REPAYMENT_RECORDED', 'POLL_CREATED', 'POLL_UPDATED', 'POLL_DELETED', 'VOTE_CAST', 'INVESTMENT_CREATED', 'INVESTMENT_UPDATED', 'INVESTMENT_APPROVED', 'INVESTMENT_CLOSED', 'INVESTMENT_CANCELLED', 'INVESTMENT_RETURN_RECORDED', 'INVESTMENT_DELETED', name='auditaction'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_user_id', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_chama_id', ['chama_id'], unique=False)
        batch_op.create_index('ix_audit_logs_loan_id', ['loan_id'], unique=False)
        batch_op.create_index('ix_audit_logs_membership_id', ['membership_id'], unique=False)
        batch_op.create_index('ix_audit_logs_target_user_id', ['target_user_id'], unique=False)

    op.create_table('investment_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('return_type', sa.Enum('DIVIDEND', 'INTEREST', 'PROFIT_SHARE', 'CAPITAL_GAIN', 'OTHER', name='returntype'), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_returns_investment_id'), ['investment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_returns_return_type'), ['return_type'], unique=False)
        batch_op.create_index('ix_return_investment_date', ['investment_id', 'return_date'], unique=False)

    op.create_table('loan_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_repayments_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_repayments_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index('ix_repayment_loan_date', ['loan_id', 'payment_date'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_options_poll_id'), ['poll_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_vote_poll_user')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_votes_poll_id'))
        batch_op.drop_index(batch_op.f('ix_votes_option_id'))

    op.drop_table('votes')
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_options_poll_id'))

    op.drop_table('poll_options')
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_index('ix_repayment_loan_date')
        batch_op.drop_index(batch_op.f('ix_loan_repayments_reference_code'))
        batch_op.drop_index(batch_op.f('ix_loan_repayments_loan_id'))

    op.drop_table('loan_repayments')
    with op.batch_alter_table('investment_returns', schema=None) as batch_op:
        batch_op.drop_index('ix_return_investment_date')
        batch_op.drop_index(batch_op.f('ix_investment_returns_return_type'))
        batch_op.drop_index(batch_op.f('ix_investment_returns_investment_id'))

    op.drop_table('investment_returns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_target_user_id')
        batch_op.drop_index('ix_audit_logs_membership_id')
        batch_op.drop_index('ix_audit_logs_loan_id')
        batch_op.drop_index('ix_audit_logs_chama_id')
        batch_op.drop_index('ix_audit_logs_actor_user_id')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_status'))
        batch_op.drop_index(batch_op.f('ix_polls_chama_id'))

    op.drop_table('polls')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_memberships_chama_id'))
        batch_op.drop_index('ix_membership_user_chama_status')

    op.drop_table('memberships')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_chama_id'))
        batch_op.drop_index(batch_op.f('ix_loans_borrower_user_id'))
        batch_op.drop_index('ix_loan_chama_borrower_status')

    op.drop_table('loans')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_status'))
        batch_op.drop_index(batch_op.f('ix_investments_name'))
        batch_op.drop_index(batch_op.f('ix_investments_investment_type'))
        batch_op.drop_index(batch_op.f('ix_investments_chama_id'))
        batch_op.drop_index('ix_investment_chama_type')
        batch_op.drop_index('ix_investment_chama_status')

    op.drop_table('investments')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_reference_code'))
        batch_op.drop_index(batch_op.f('ix_contributions_chama_id'))
        batch_op.drop_index('ix_contribution_chama_user_date')

    op.drop_table('contributions')
    with op.batch_alter_table('chama_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chama_invites_token'))
        batch_op.drop_index(batch_op.f('ix_chama_invites_status'))
        batch_op.drop_index(batch_op.f('ix_chama_invites_phone_number'))
        batch_op.drop_index(batch_op.f('ix_chama_invites_invited_user_id'))
        batch_op.drop_index(batch_op.f('ix_chama_invites_email'))
        batch_op.drop_index(batch_op.f('ix_chama_invites_chama_id'))

    op.drop_table('chama_invites')
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamas_status'))
        batch_op.drop_index(batch_op.f('ix_chamas_slug'))
        batch_op.drop_index(batch_op.f('ix_chamas_name'))

    op.drop_table('chamas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
